name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: gcc -Wall -Wextra -o BatteryHealthMonitoringTester ./Test/BatteryHealthMonitoring/*.c
      
    - name: run
      run: ./BatteryHealthMonitoringTester
